[package]
name = "binary_analysis"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
goblin = "0.5"
anyhow = "1.0"
capstone = "0.11.0"